### ISSUE TITLE
Sentry 에러전송 활성화 토글이 가능했으면 좋겠습니다.

### ISSUE THREAD

**Issue by Waterticket** [rx-apps/sentry#1]
관리자 페이지에서 Sentry 로그 전송 활성화/비활성화를 선택할 수 있으면 좋겠습니다

**Comment by nemorize** [comment]
곧 추가하도록 하겠습니다.

Sentry DSN으로 연결에 실패할 경우 로그 전송이 자동으로 중단됩니다.
추가 전까지는 URL 앞에 ! 등을 붙여 임시로 비활성화 처리할 수 있습니다.

**Comment by Waterticket** [comment]
좋은 모듈 만들어주셔서 감사합니다 :D

**Comment by nemorize** [comment]
기능 추가되었습니다.
감사합니다.
